### ISSUE TITLE
"Starting Raven" doesn't continue

### ISSUE THREAD

**Issue by cjprogamer** [cloudlibz/raven#2]
**When I run the command `go run raven.go` It doesn't continue and stucks here ...**
![Screenshot from 2020-01-08 08-19-23](https://user-images.githubusercontent.com/41909955/71972601-f8ac0c80-3232-11ea-838c-9f348ab93f58.png)

**Comment by TRomesh** [comment]
Hi, @cjprogamer that's all. It's not stuck its running without any issues, just make a get request to `localhost:3003` or  `localhost:3003/api/v1/metrics` to check if the application is working. Those endpoints will send some text in response

**Comment by rajikaimal** [comment]
Closing this as this is the expected behavior as of now
